USE controle_de_nt;


SELECT * FROM base_de_notas;
SELECT * FROM usuario;
SELECT * FROM filial;
SELECT * FROM controle_fixo;
SELECT * FROM controle_variavel;
SELECT * FROM LIBERACAO_DE_NOTAS;
SELECT * FROM NOTAS_ARQUIVADAS;
SELECT * FROM NOTAS_MENSAIS;

ALTER TABLE base_de_notas DROP FOREIGN KEY fk_usuario;


ALTER TABLE base_de_notas
DROP COLUMN Criado_por;

ALTER TABLE NOTAS_MENSAIS MODIFY observacao TEXT NOT NULL;
ALTER TABLE base_de_notas MODIFY Criado_por VARCHAR(99) NOT NULL;

ALTER TABLE base_de_notas 
ADD COLUMN Criado_por VARCHAR(99) NOT NULL;

INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (1, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'MATRIZ',  30581433000149, 'PADRE MATHIAS','CARIACICA', 'ES');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (2, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'SAO PAULO',  30581433000191, 'CID. JARDIM CUMBICA','GUARULHOS', 'SP');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (3, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'F.ALAGOAS',  30581433000734, 'ZONA RURAL','PILAR', 'AL');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (4, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'F.BAHIA',  30581433000815,'CAMINHO DAS ARVORES', 'SALVADOR', 'BA');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (5, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'FILIAL ES',  30581433000904,'PORTO ENGENHO', 'CARIACICA', 'ES');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (6, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'FILIAL SERRA - ES ',  30581433000110,'TIMS', 'SERRA', 'ES');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (7, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'F.CAMPO BOM RS',  30581433001030,'INDUSTRIAL','CAMPO BOM', 'RS');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (8, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'F.CURITIBA PR',  30581433001200, 'CIDADE INDUSTRIAL','CURITIBA', 'PR');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (9, 'TRANSILVA TRASPORTES E LOGISTICA LTDA', 'F.ITUMBIARA',  30581433001382,'NOSSA SENHORA DA SAU','ITUMBIARA', 'GO');

/*DESTAQUE*/
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (10, 'DESTAQUE TRANSPORTES E LOGISTICA LTDA', 'DTL -ES',  31467699000128,'PADRE MATHIAS','CARIACICA', 'ES');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (11, 'DESTAQUE TRANSPORTES E LOGISTICA LTDA', 'DTL -SP',  31467699000390,'CID.JARDIM CUMBICA','GUARULHOS', 'SP');

/*AUTOVIVA*/
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (12, 'AUTOVIVA CAMINHOES E ONIBUS LTDA', 'AUTOVIVA CAMINHOES',  23595615000103,'PORTO ENGENHO','CARIACICA', 'ES');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (13, 'AUTOVIVA SERVICOS LTDA', 'AUTOVIVA SERVICOS',  21270872000140,'PORTO ENGENHO','CARIACICA', 'ES');

/*CODEPE*/
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (14, 'CODEPE-CENTRO OPER.LOG.PORTO ENGENHO L', 'CODEPE',  13411696000190,'PADRE MATHIAS','CARIACICA', 'ES');

/*GEPAX*/
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (15, 'GEPAX TRANSPORTES E LOGISTICA LTDA', 'GEPAX',  42039523000191,'NOVA ROSA DA PENHA','CARIACICA', 'ES');

/*JAPP*/
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (16, 'JAPP PARTICIPACOES LTDA', 'JAPP',  11486608000194,'ITAPUA','VILA VELHA', 'ES');
INSERT INTO filial (Filial_codigo,Razao_social,Nome_fantasia,CNPJ,Bairro,Municipio,Estado) VALUES (17, 'JAPP EMPREENDIMENTOS E PARTICIPACOES LTDA', 'JAPP PARTICIPACOES',  50247546000110,'PADRE MATHIAS','CARIACICA', 'ES');


SELECT * FROM notas_mensais;

INSERT INTO notas_mensais (filial, fornecedor, investimento, data_emissao, data_vencimento, pedido, nota_fiscal, situacao, observacao, mes_referencia)
VALUES ('GEPAX', 'EMBRATEL/CLARO S.A/TELMEX', 'INTERNET', NULL, NULL, NULL, NULL, NULL, 
'EQUIPAMENTO DE WIFI - REDE GEPAX - 1 NOTA - NO VALOR FIXO DE R$ 278,25 - ALIQUOTA 2,90% - ISS 8,06 - REFERENTE AO SERVIÇO DE EQUIPAMENTO EMBRATEL/E GERENCIAMENTO DE ACESSO A INTERNET/WIFI NO LOCAL', 
'2025-01-01');


UPDATE Notas_mensais
SET observacao = 'GERENCIA DE REDE'
WHERE idnotas_mensais = 17;

ALTER TABLE filial
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE notas_mensais
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE base_de_notas
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE controle_fixo
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE controle_variavel
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE produto_ou_servico
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE usuario
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE notas_arquivadas
ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
