-- MySQL Script generated by MySQL Workbench
-- Sun Nov 17 16:20:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema controle_de_nt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controle_de_nt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle_de_nt` DEFAULT CHARACTER SET utf8mb4 ;
USE `controle_de_nt` ;

-- -----------------------------------------------------
-- Table `controle_de_nt`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(99) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `nome` VARCHAR(99) NOT NULL,
  `status` TINYINT NULL,
  `token_recuperacao` VARCHAR(99) NULL,
  `permissoes` ENUM('admin', 'usuario') NULL,
  `base_de_notas_idBase_de_Notas` INT(111) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_base_de_notas1_idx` (`base_de_notas_idBase_de_Notas` ASC),
  CONSTRAINT `fk_usuario_base_de_notas1`
    FOREIGN KEY (`base_de_notas_idBase_de_Notas`)
    REFERENCES `controle_de_nt`.`base_de_notas` (`idBase_de_Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_de_nt`.`base_de_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`base_de_notas` (
  `idBase_de_Notas` INT(11) NOT NULL AUTO_INCREMENT,
  `Filial_codigo` INT(11) NOT NULL,
  `Razao_social` VARCHAR(99) NOT NULL,
  `Nome_fantasia` VARCHAR(99) NOT NULL,
  `Investimento` VARCHAR(45) NOT NULL,
  `Fornecedor` VARCHAR(99) NOT NULL,
  `Pedido` INT(11) NOT NULL,
  `Data_de_emissao` DATE NOT NULL,
  `Data_de_vencimento` DATE NOT NULL,
  `NF_DANFE` VARCHAR(99) NOT NULL,
  `Protocolo` VARCHAR(60) NULL DEFAULT NULL,
  `ValorMesAtual` FLOAT NOT NULL,
  `ValorUltMes` FLOAT NULL DEFAULT NULL,
  `Parcelas` VARCHAR(99) NULL DEFAULT NULL,
  `Pagamento` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  `Conta` INT(11) NOT NULL,
  `Observacao` TEXT NULL DEFAULT NULL,
  `Criado_por` VARCHAR(99) NOT NULL,
  PRIMARY KEY (`idBase_de_Notas`),
  UNIQUE INDEX `idBase_de_Notas_UNIQUE` (`idBase_de_Notas` ASC),
  INDEX `fk_usuario_idx` (`Criado_por` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`Criado_por`)
    REFERENCES `controle_de_nt`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `controle_de_nt`.`filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`filial` (
  `idbase_filial` INT(11) NOT NULL AUTO_INCREMENT,
  `Filial_codigo` INT(11) NOT NULL,
  `Razao_social` VARCHAR(99) NOT NULL,
  `Nome_fantasia` VARCHAR(99) NOT NULL,
  `CNPJ` CHAR(14) NOT NULL,
  `Bairro` VARCHAR(99) NOT NULL,
  `Municipio` VARCHAR(99) NOT NULL,
  `Estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`idbase_filial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `controle_de_nt`.`base_de_notas_has_filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`base_de_notas_has_filial` (
  `Base_de_Notas_idBase_de_Notas` INT(11) NOT NULL,
  `Filial_idbase_filial` INT(11) NOT NULL,
  `Base_de_Notas_has_Filialcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Base_de_Notas_idBase_de_Notas`, `Filial_idbase_filial`),
  INDEX `fk_Base_de_Notas_has_Filial_Filial_idx` (`Filial_idbase_filial` ASC),
  INDEX `fk_Base_de_Notas_has_Filial_Base_de_Notas_idx` (`Base_de_Notas_idBase_de_Notas` ASC),
  CONSTRAINT `fk_Base_de_Notas_has_Filial_Base_de_Notas`
    FOREIGN KEY (`Base_de_Notas_idBase_de_Notas`)
    REFERENCES `controle_de_nt`.`base_de_notas` (`idBase_de_Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Base_de_Notas_has_Filial_Filial`
    FOREIGN KEY (`Filial_idbase_filial`)
    REFERENCES `controle_de_nt`.`filial` (`idbase_filial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `controle_de_nt`.`controle_fixo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`controle_fixo` (
  `Controle_fixo` INT(11) NOT NULL AUTO_INCREMENT,
  `Filial_codigo` INT(11) NOT NULL,
  `Razao_social` VARCHAR(95) NOT NULL,
  `Nome_fantasia` VARCHAR(99) NOT NULL,
  `Fornecedor` VARCHAR(95) NOT NULL,
  `Investimento` VARCHAR(45) NOT NULL,
  `Data_de_emissao` DATE NOT NULL,
  `Data_de_vencimento` DATE NOT NULL,
  `Nota_fiscal` VARCHAR(99) NOT NULL,
  `Pedido` INT(11) NOT NULL,
  `Observacao` TEXT NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  `Base_de_Notas_idBase_de_Notas` INT(11) NOT NULL,
  PRIMARY KEY (`Controle_fixo`),
  INDEX `fk_Controle_Mensais_Base_de_Notas1_idx` (`Base_de_Notas_idBase_de_Notas` ASC),
  CONSTRAINT `fk_Controle_Mensais_Base_de_Notas1`
    FOREIGN KEY (`Base_de_Notas_idBase_de_Notas`)
    REFERENCES `controle_de_nt`.`base_de_notas` (`idBase_de_Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `controle_de_nt`.`controle_variavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`controle_variavel` (
  `Controle_variavel` INT(11) NOT NULL AUTO_INCREMENT,
  `Filial_codigo` INT(11) NOT NULL,
  `Razao_social` VARCHAR(95) NOT NULL,
  `Nome_fantasia` VARCHAR(99) NOT NULL,
  `Fornecedor` VARCHAR(95) NOT NULL,
  `Investimento` VARCHAR(45) NOT NULL,
  `Data_de_emissao` DATE NOT NULL,
  `Data_de_vencimento` DATE NOT NULL,
  `Nota_fiscal` VARCHAR(45) NOT NULL,
  `Pedido` INT(11) NOT NULL,
  `Observacao` TEXT NOT NULL,
  `Situacao` VARCHAR(45) NOT NULL,
  `Base_de_Notas_idBase_de_Notas` INT(11) NOT NULL,
  PRIMARY KEY (`Controle_variavel`),
  INDEX `fk_Controle_variavel_Base_de_Notas1_idx` (`Base_de_Notas_idBase_de_Notas` ASC),
  CONSTRAINT `fk_Controle_variavel_Base_de_Notas1`
    FOREIGN KEY (`Base_de_Notas_idBase_de_Notas`)
    REFERENCES `controle_de_nt`.`base_de_notas` (`idBase_de_Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `controle_de_nt`.`liberacao_de_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`liberacao_de_notas` (
  `liberacao_notas_id` INT(11) NOT NULL AUTO_INCREMENT,
  `Filial_codigo` INT(11) NOT NULL,
  `Razao_social` VARCHAR(50) NOT NULL,
  `Nome_fantasia` VARCHAR(99) NOT NULL,
  `Investimento` VARCHAR(99) NOT NULL,
  `Pedido` INT(11) NOT NULL,
  `ValorMesAtual` FLOAT NOT NULL,
  `ValorMePass` FLOAT NULL DEFAULT NULL,
  `NF_DANFE` VARCHAR(99) NOT NULL,
  `Data_de_vencimento` DATE NOT NULL,
  `Observacao` TEXT NOT NULL,
  PRIMARY KEY (`liberacao_notas_id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


CREATE TABLE IF NOT EXISTS `controle_de_nt`.`Notas_Arquivadas` (
  `idNotas_Arquivadas` INT NOT NULL AUTO_INCREMENT,
  `Razao_social` VARCHAR(50) NOT NULL,
  `Data_Upload` DATE NOT NULL,
  `Arquivo` LONGBLOB NOT NULL,
  PRIMARY KEY (`idNotas_Arquivadas`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `controle_de_nt`.`notas_mensais` (
  `idnotas_mensais` INT NOT NULL AUTO_INCREMENT,
  `filial` VARCHAR(50) NOT NULL,
  `fornecedor` VARCHAR(255) NOT NULL,
  `investimento` VARCHAR(100) NOT NULL,
  `data_emissao` DATE,
  `data_vencimento` DATE,
  `pedido` VARCHAR(45),
  `nota_fiscal` VARCHAR(50),
  `situacao` VARCHAR(45),
  `observacao` TEXT NOT NULL,
  `mes_referencia` DATE NOT NULL,
  PRIMARY KEY (`idnotas_mensais`))
ENGINE = InnoDB;

/*
CREATE TABLE dados_fixos (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `filial` VARCHAR(50),
    `fornecedor` VARCHAR(50),
    `grupo` VARCHAR(50),
    `investimento` VARCHAR(50)
);
*//*
CREATE TABLE dados_variaveis (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `dados_fixo_id` INT,
    `data_emissao` DATE,
    `data_vencimento` DATE,
    `nota_fiscal` VARCHAR(20),
    `pedido` VARCHAR(20),
    `situacao` VARCHAR(50),
    `mes_referencia` DATE,
    FOREIGN KEY (dados_fixo_id) REFERENCES dados_fixos(id)
);
*/

-- -----------------------------------------------------
-- Table `controle_de_nt`.`Produto_ou_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_de_nt`.`Produto_ou_servico` (
  `idProduto_ou_servico` INT NOT NULL,
  `Produto_ou_servico` VARCHAR(45) NOT NULL,
  `Filial_codigo` INT(11) NOT NULL,
  `Razao_social` VARCHAR(99) NOT NULL,
  `Pedido` INT(11) NOT NULL,
  `base_de_notas_idBase_de_Notas` INT(11) NOT NULL,
  PRIMARY KEY (`idProduto_ou_servico`),
  INDEX `fk_Produto_ou_servico_base_de_notas1_idx` (`base_de_notas_idBase_de_Notas` ASC),
  CONSTRAINT `fk_Produto_ou_servico_base_de_notas1`
    FOREIGN KEY (`base_de_notas_idBase_de_Notas`)
    REFERENCES `controle_de_nt`.`base_de_notas` (`idBase_de_Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
